language: node_js

node_js: "0.10"

install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g coveralls
  - npm install -g mocha-lcov-reporter
  - npm install
services:
  - mongodb
  - redis-server
before_install:
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
script:
  - istanbul cover _mocha --report lcovonly
after_script:
  - cat ./coverage/lcov.info | coveralls
