language: node_js

node_js: "0.10"

install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g coveralls
  - npm install
services:
  - mongodb
script:
  - istanbul cover --report lcovonly mocha
after_script:
  - cat ./coverage/lcov.info | coveralls/bin/coveralls.js
